id = "leblackque"
name = "Le Blackque Theme"
version = "1.0.1"
schema_version = 1
authors = ["Grant Miner <gx0r@proton.me>"]
description = "A dark and elegant theme"
repository = "https://github.com/gx0r/leblackque"
